# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-02 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_total',
            name='promocode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Loma.promocode_model'),
        ),
    ]
