# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_total_promocode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order_total',
            name='promocode',
        ),
        migrations.AlterField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cartitem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.order_total'),
        ),
    ]
