# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_auto_20190203_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='order_total',
            name='updated',
        ),
        migrations.AddField(
            model_name='order',
            name='timeslot',
            field=models.CharField(choices=[('Anytime', 'Anytime'), ('first_slot', '7:00am - 10:00am'), ('secand_slot', '10:am - 1:00am'), ('third_slot', '1:00am - 4:00am'), ('fourth_slot', '4:00am - 7:00am')], default='Any-time', max_length=120),
        ),
        migrations.AddField(
            model_name='order_total',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
