# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 23:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0005_auto_20190204_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='timeslot',
            field=models.CharField(choices=[('Anytime', 'Anytime'), ('first_slot', '7:00am - 10:00am'), ('secand_slot', '10:am - 1:00pm'), ('third_slot', '1:00pm - 4:00pm'), ('fourth_slot', '4:00pm - 7:00pm')], default='Any-time', max_length=120),
        ),
    ]
