# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 12:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0006_auto_20190204_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order_total',
            old_name='order_id',
            new_name='order_name',
        ),
    ]
