# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20190203_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carttotal',
            name='Total',
            field=models.FloatField(default=0.0),
        ),
    ]
