# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 13:34
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20190203_1843'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='cartitem',
            managers=[
                ('sub', django.db.models.manager.Manager()),
            ],
        ),
    ]
