# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 13:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20190203_1904'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='sub_total',
            new_name='price',
        ),
    ]
