# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 18:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_auto_20190203_1839'),
        ('cart', '0006_auto_20190204_2325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='products.product'),
        ),
    ]
