# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dp_order_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_orders', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='dp_vehicle_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vechile_registration_number', models.CharField(max_length=120)),
                ('Image_cv', models.ImageField(null=True, upload_to=b'')),
                ('Driving_license_image', models.ImageField(upload_to=b'')),
                ('licenseno', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='dp_master',
            name='username',
            field=models.CharField(help_text='Required', max_length=250, unique=True),
        ),
        migrations.AddField(
            model_name='dp_vehicle_model',
            name='dp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.dp_master'),
        ),
        migrations.AddField(
            model_name='dp_order_model',
            name='dp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dp.dp_master'),
        ),
    ]
