# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_auto_20190204_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp_vehicle_model',
            name='Driving_license_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
    ]
