# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 06:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0004_dp_order_model_status_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='dp_order_model',
            name='order_by_loma',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
