# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0005_dp_order_model_order_by_loma'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dp_order_model',
            old_name='order_by_loma',
            new_name='order_id',
        ),
        migrations.AddField(
            model_name='dp_order_model',
            name='Customer_address',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dp_order_model',
            name='Customer_name',
            field=models.CharField(default=2, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dp_order_model',
            name='ordered_loma_name',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dp_order_model',
            name='ordered_loma_zone',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
