# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0006_auto_20190205_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dp_order_model',
            name='ordered_loma_zone',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
