# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 05:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loma_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loma_name', models.CharField(max_length=120)),
                ('loma_email', models.EmailField(max_length=60)),
                ('loma_password', models.CharField(max_length=120)),
                ('loma_permanent_Address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=30)),
                ('Loma_mandi_name', models.CharField(max_length=120)),
                ('loma_zone', models.CharField(max_length=120)),
                ('loma_mobile_no', models.IntegerField(default=0.0)),
                ('loma_slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
    ]
