# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190203_0740'),
        ('order', '0003_auto_20190203_0740'),
        ('user_model', '0006_auto_20190201_2041'),
        ('vendor', '0004_vendor_daily_pl_updated'),
        ('Loma', '0002_loma_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_price_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_list_date', models.DateField(auto_now_add=True)),
                ('price_list_time', models.DateTimeField(auto_now_add=True)),
                ('offer_price', models.FloatField(default=10.5)),
                ('list_price', models.IntegerField(default=0.0)),
                ('margin', models.FloatField(default=0.0)),
                ('total_available_quantity', models.FloatField(default=50.5)),
                ('rating', models.IntegerField(default=2.5)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendor_daily_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor_daily_PL')),
            ],
        ),
        migrations.CreateModel(
            name='daily_price_list_approoved_by_loma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_price', models.FloatField()),
                ('list_price', models.FloatField()),
                ('verified', models.BooleanField(default=False)),
                ('Loma_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loma.Loma_master')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
                ('vendor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor_daily_PL')),
            ],
        ),
        migrations.CreateModel(
            name='Loma_operation_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=120)),
                ('Loma_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Loma.Loma_master')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_model.address')),
                ('order_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='order.Order')),
            ],
        ),
    ]
