# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0004_auto_20190203_0825'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='approved_PL_loma',
            new_name='approved_pl_by_loma',
        ),
    ]
