# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 10:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0006_loma_attendance_model_md_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loma_attendance_model',
            name='today_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
