# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0012_auto_20190203_1754'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_pl_by_loma',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
