# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0013_approved_pl_by_loma_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_pl_by_loma',
            name='list_price',
            field=models.FloatField(default=2),
            preserve_default=False,
        ),
    ]
