# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor', '0004_vendor_daily_pl_updated'),
        ('Loma', '0015_approved_pl_by_loma_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_pl_by_loma',
            name='vendor_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='vendor.vendor_daily_PL'),
            preserve_default=False,
        ),
    ]
