# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20190203_0740'),
        ('Loma', '0016_approved_pl_by_loma_vendor_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='approved_pl_by_loma',
            name='product_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
    ]
