# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0017_approved_pl_by_loma_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved_pl_by_loma',
            name='vendor_id',
        ),
    ]
