# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0018_remove_approved_pl_by_loma_vendor_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='approved_pl_by_loma',
            name='list_price',
        ),
    ]
