# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0021_auto_20190203_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promocode_model',
            name='promocode_name',
            field=models.CharField(max_length=11),
        ),
    ]
