# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 11:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0022_auto_20190204_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_price_list',
            name='product',
        ),
    ]
