# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dp', '0002_auto_20190204_1859'),
        ('Loma', '0024_auto_20190204_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='loma_operation_model',
            name='dp_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='dp.dp_master'),
            preserve_default=False,
        ),
    ]
