# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-04 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0025_loma_operation_model_dp_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loma_operation_model',
            old_name='Zone',
            new_name='loma_Zone',
        ),
        migrations.RenameField(
            model_name='loma_operation_model',
            old_name='address',
            new_name='user_address',
        ),
        migrations.RenameField(
            model_name='loma_operation_model',
            old_name='order_id',
            new_name='user_order_id',
        ),
    ]
