# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0027_auto_20190205_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_price_list',
            name='loma_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='Loma.Loma_master'),
            preserve_default=False,
        ),
    ]
