# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0028_daily_price_list_loma_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MD_model',
            new_name='md',
        ),
    ]
