# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0029_auto_20190205_1945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='md',
            name='vendor',
        ),
    ]
