# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-05 23:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Loma', '0032_auto_20190205_2016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_price_list',
            name='vendor_id',
        ),
    ]
