# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 07:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_daily_price_list_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daily_price_list',
            name='product',
        ),
        migrations.DeleteModel(
            name='Daily_price_list',
        ),
    ]
