# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-03 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_product_price_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_price',
            name='price',
            field=models.PositiveIntegerField(default=0.0),
        ),
    ]
